# Generated by Django 5.1.6 on 2025-03-14 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartebancaire',
            name='cvc',
            field=models.CharField(default='856', max_length=3),
        ),
        migrations.AlterField(
            model_name='cartebancaire',
            name='date_expiration',
            field=models.DateField(default=datetime.date(2027, 3, 14)),
        ),
        migrations.AlterField(
            model_name='client',
            name='solde',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
        ),
    ]
