# Generated by Django 5.1.6 on 2025-02-21 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeAgent',
            fields=[
                ('type_agent_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeClient',
            fields=[
                ('type_client_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeCompte',
            fields=[
                ('type_compte_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeDocument',
            fields=[
                ('type_document_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOffre',
            fields=[
                ('type_offre_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeTransaction',
            fields=[
                ('type_transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(blank=True, max_length=50, null=True)),
                ('adresse', models.CharField(max_length=100)),
                ('numero_identite', models.CharField(max_length=20, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('type_client_id', models.IntegerField(default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActionNFC',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_lecture', models.DateTimeField()),
                ('statut_lecture', models.CharField(max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_ouverture', models.DateField()),
                ('statut', models.CharField(max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
                ('type_compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.typecompte')),
            ],
        ),
        migrations.CreateModel(
            name='CreditBancaire',
            fields=[
                ('credit_id', models.AutoField(primary_key=True, serialize=False)),
                ('montant_credite', models.IntegerField()),
                ('taux_interet', models.IntegerField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut_credit', models.CharField(max_length=50)),
                ('penalite', models.IntegerField()),
                ('solde_restant', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='DemandeCompteBancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('numero_identite', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_comptes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Echeance',
            fields=[
                ('echeance_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_echeance', models.DateField()),
                ('montant_echeance', models.IntegerField()),
                ('statut_echeance', models.CharField(max_length=50)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.creditbancaire')),
            ],
        ),
        migrations.CreateModel(
            name='ResultatIA',
            fields=[
                ('resultat_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_analyse', models.CharField(max_length=50)),
                ('resultat', models.CharField(max_length=50)),
                ('date_analyse', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('agent_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('role', models.CharField(max_length=50)),
                ('type_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.typeagent')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('chemin_fichier', models.CharField(max_length=255)),
                ('date_upload', models.DateField()),
                ('statut_verif', models.CharField(max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
                ('type_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.typedocument')),
            ],
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('offre_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_proposition', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
                ('type_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.typeclient')),
                ('type_offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.typeoffre')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('montant', models.IntegerField()),
                ('date_transaction', models.DateTimeField(auto_now_add=True)),
                ('statut_transaction', models.CharField(max_length=50)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.compte')),
                ('type_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.typetransaction')),
            ],
        ),
    ]
