# Generated by Django 5.1.6 on 2025-03-08 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_employe'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='password_client',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='demandecomptebancaire',
            name='situation_familliale',
            field=models.CharField(choices=[('Célibataire', 'Célibataire'), ('Marié(e)', 'Marié(e)'), ('Divorcé(e)', 'Divorcé(e)'), ('Veuf/veuve', 'Veuf/veuve')], max_length=15),
        ),
    ]
