# Generated by Django 5.1.6 on 2025-03-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_cartebancaire_cvc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartebancaire',
            name='cvc',
            field=models.CharField(default='621', max_length=3),
        ),
    ]
