# Generated by Django 5.1.6 on 2025-03-09 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_client_password_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandecomptebancaire',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
