# Generated by Django 5.1.6 on 2025-02-21 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_typeagent_typeclient_typecompte_typedocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compte',
            name='Document',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='compte',
            name='nom',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
