# Generated by Django 5.1.6 on 2025-02-22 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_compte_document_compte_nom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compte',
            name='Document',
        ),
        migrations.RemoveField(
            model_name='compte',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='document',
            name='chemin_fichier',
        ),
        migrations.AddField(
            model_name='document',
            name='demande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.demandecomptebancaire'),
        ),
        migrations.AddField(
            model_name='document',
            name='fichier',
            field=models.FileField(default=3, max_length=255, upload_to=''),
            preserve_default=False,
        ),
    ]
