# Generated by Django 5.1.6 on 2025-03-09 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_demandecomptebancaire_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandecomptebancaire',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo/'),
        ),
    ]
