# Generated by Django 5.1.6 on 2025-03-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_cartebancaire_cvc'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='videoconference',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='cartebancaire',
            name='cvc',
            field=models.CharField(default='544', max_length=3),
        ),
    ]
