# Generated by Django 5.1.6 on 2025-03-11 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_is_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_employee',
        ),
    ]
