# Generated by Django 5.1.6 on 2025-02-22 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_document_client_document_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='date_upload',
        ),
    ]
