# Generated by Django 5.1.6 on 2025-03-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_user_is_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
