# Generated by Django 5.1.6 on 2025-03-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_employe_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='typedocument',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
