# Generated by Django 5.1.6 on 2025-02-27 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_client_compte_client_id_client_client_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='date_creation',
            new_name='created_at',
        ),
    ]
