# Generated by Django 5.1.6 on 2025-03-11 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_create_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compte',
            old_name='id_client',
            new_name='client_id',
        ),
        migrations.CreateModel(
            name='cartebancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleint_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
            ],
        ),
    ]
