# Generated by Django 5.1.6 on 2025-03-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_status_demandecomptebancaire_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandecomptebancaire',
            name='Nationalité',
            field=models.CharField(default='Non spécifié', max_length=20),
        ),
        migrations.AddField(
            model_name='demandecomptebancaire',
            name='Nom_mère',
            field=models.CharField(default='Non spécifié', max_length=20),
        ),
        migrations.AddField(
            model_name='demandecomptebancaire',
            name='Pays_naissance',
            field=models.CharField(default='Non spécifié', max_length=20),
        ),
        migrations.AddField(
            model_name='demandecomptebancaire',
            name='Prénom_mère',
            field=models.CharField(default='Non spécifié', max_length=20),
        ),
        migrations.AddField(
            model_name='demandecomptebancaire',
            name='Prénom_père',
            field=models.CharField(default='Non spécifié', max_length=20),
        ),
        migrations.AddField(
            model_name='demandecomptebancaire',
            name='civilité',
            field=models.CharField(choices=[('Mr', 'Monsieur'), ('Mme', 'Madame')], default='Mr', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demandecomptebancaire',
            name='situation_familliale',
            field=models.CharField(choices=[('Célibataire', 'Célibataire'), ('Marié', 'Marié'), ('Divorcé', 'Divorcé'), ('Mariée', 'Mariée'), ('Divorcée', 'Divorcée'), ('Veuf', 'Veuf'), ('Veuve', 'Veuve')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
