# Generated by Django 5.1.6 on 2025-03-12 01:20

import api.models
import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_id_client_compte_client_id_cartebancaire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartebancaire',
            old_name='cleint_id',
            new_name='client_id',
        ),
        migrations.AddField(
            model_name='cartebancaire',
            name='cvc',
            field=models.CharField(default='712', max_length=3),
        ),
        migrations.AddField(
            model_name='cartebancaire',
            name='date_expiration',
            field=models.DateField(default=datetime.date(2027, 3, 12)),
        ),
        migrations.AddField(
            model_name='cartebancaire',
            name='date_ouverture',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cartebancaire',
            name='frais_carte',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='cartebancaire',
            name='frais_payes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartebancaire',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cartebancaire',
            name='numero_carte',
            field=models.CharField(default=api.models.generate_numero_carte, editable=False, max_length=16, unique=True),
        ),
        migrations.AddField(
            model_name='cartebancaire',
            name='plafond_paiement',
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cartebancaire',
            name='plafond_retrait',
            field=models.DecimalField(decimal_places=2, default=2000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cartebancaire',
            name='statut_carte',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='cartebancaire',
            name='type_carte',
            field=models.CharField(choices=[('VISA', 'Visa'), ('MASTERCARD', 'MasterCard'), ('VISA_PLATINUM', 'Visa Platinum'), ('MASTERCARD_ELITE', 'MasterCard World Elite'), ('AMEX', 'American Express'), ('AMEX_GOLD', 'American Express Gold')], default='VISA', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='solde',
            field=models.DecimalField(decimal_places=2, default=5000000, max_digits=15),
            preserve_default=False,
        ),
    ]
