# Generated by Django 5.1.6 on 2025-03-02 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_demandecomptebancaire_nationalité_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandecomptebancaire',
            name='Nationalité',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='demandecomptebancaire',
            name='Nom_mère',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='demandecomptebancaire',
            name='Pays_naissance',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='demandecomptebancaire',
            name='Prénom_mère',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='demandecomptebancaire',
            name='Prénom_père',
            field=models.CharField(max_length=20),
        ),
    ]
