# Generated by Django 5.1.6 on 2025-03-12 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_cleint_id_cartebancaire_client_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartebancaire',
            name='cvc',
            field=models.CharField(default='164', max_length=3),
        ),
    ]
