# Generated by Django 5.1.6 on 2025-03-12 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_cartebancaire_cvc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartebancaire',
            name='cvc',
            field=models.CharField(default='249', max_length=3),
        ),
        migrations.AddConstraint(
            model_name='cartebancaire',
            constraint=models.UniqueConstraint(fields=('client_id', 'type_carte'), name='unique_carte_par_type_par_client'),
        ),
    ]
