# Generated by Django 5.1.6 on 2025-03-02 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_demandecomptebancaire_nationalité_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demandecomptebancaire',
            old_name='statut',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='document',
            name='statut_verif',
            field=models.CharField(choices=[('not verified', 'non vérifié'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='not verified', max_length=15),
        ),
    ]
