# Generated by Django 5.1.6 on 2025-03-12 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_cartebancaire_cvc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartebancaire',
            name='cvc',
            field=models.CharField(default='195', max_length=3),
        ),
        migrations.AlterField(
            model_name='cartebancaire',
            name='statut_carte',
            field=models.CharField(choices=[('active', 'Active'), ('expirée', 'Expirée'), ('bloquée', 'Bloquée')], default='active', max_length=20),
        ),
    ]
