# Generated by Django 5.1.6 on 2025-03-05 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_nom_mère_demandecomptebancaire_nom_mere_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typeclient',
            old_name='type_client_id',
            new_name='id',
        ),
        migrations.AddField(
            model_name='demandecomptebancaire',
            name='type_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.typeclient'),
        ),
        migrations.AlterField(
            model_name='typeclient',
            name='nom_type',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
