# Generated by Django 5.1.6 on 2025-03-03 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_nom_mère_demandecomptebancaire_nom_mere_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandecomptebancaire',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
