# Generated by Django 5.1.6 on 2025-03-05 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_type_client_id_typeclient_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeclient',
            name='nom_type',
            field=models.CharField(choices=[(1, 'Étudiant'), (2, 'Commerçant'), (3, 'Professionnel'), (4, 'Personnel'), (5, 'Jeune/Enfant')], max_length=50, unique=True),
        ),
    ]
