# Generated by Django 5.1.6 on 2025-03-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_typeclient_nom_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeclient',
            name='nom_type',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
