# Generated by Django 5.1.6 on 2025-03-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_cartebancaire_cvc_alter_employe_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartebancaire',
            name='cvc',
            field=models.CharField(default='470', max_length=3),
        ),
    ]
