# Generated by Django 5.1.6 on 2025-03-06 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_client_type_client_id_client_type_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='id',
        ),
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.CharField(default=10920918301982, editable=False, max_length=16, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
