# Generated by Django 5.1.6 on 2025-03-05 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_user_is_employe_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_employe',
        ),
    ]
