# Generated by Django 5.1.6 on 2025-03-05 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_user_is_employe'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_employe',
            field=models.BooleanField(default=False),
        ),
    ]
