# Generated by Django 5.1.6 on 2025-03-06 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_rename_client_id_compte_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='compte',
        ),
        migrations.DeleteModel(
            name='Compte',
        ),
    ]
