# Generated by Django 5.1.6 on 2025-03-06 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_transaction_compte_delete_compte'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TypeCompte',
        ),
    ]
