# Generated by Django 5.1.6 on 2025-03-13 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_cartebancaire_cvc'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='emp_id',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cartebancaire',
            name='cvc',
            field=models.CharField(default='919', max_length=3),
        ),
        migrations.CreateModel(
            name='VideoConference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_url', models.TextField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('done', 'Terminée'), ('canceled', 'Annulée')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conferences_client', to='api.client')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conferences_employe', to='api.employe')),
            ],
            options={
                'unique_together': {('client', 'employe', 'status')},
            },
        ),
    ]
