# Generated by Django 5.1.6 on 2025-03-06 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_delete_typecompte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('compte_id', models.AutoField(primary_key=True, serialize=False)),
                ('solde', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
            ],
        ),
    ]
