# Generated by Django 5.1.6 on 2025-03-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_employe_emp_id_alter_cartebancaire_cvc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='id',
        ),
        migrations.AlterField(
            model_name='cartebancaire',
            name='cvc',
            field=models.CharField(default='308', max_length=3),
        ),
        migrations.AlterField(
            model_name='employe',
            name='emp_id',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
