# Generated by Django 5.1.6 on 2025-03-06 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_compte'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeCompte',
            fields=[
                ('type_compte_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='type_client',
        ),
        migrations.RemoveField(
            model_name='compte',
            name='client',
        ),
        migrations.RemoveField(
            model_name='compte',
            name='compte_id',
        ),
        migrations.AddField(
            model_name='client',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1212, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='type_client_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='compte',
            name='client_id',
            field=models.ForeignKey(default=19191919191919, on_delete=django.db.models.deletion.CASCADE, to='api.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compte',
            name='date_ouverture',
            field=models.DateField(default='2024-06-03'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compte',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compte',
            name='id',
            field=models.BigAutoField(auto_created=True, default=3, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compte',
            name='statut',
            field=models.CharField(default='approuved', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='compte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.compte'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.CharField(blank=True, editable=False, max_length=16, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='compte',
            name='type_compte',
            field=models.ForeignKey(default='étudiant', on_delete=django.db.models.deletion.CASCADE, to='api.typecompte'),
            preserve_default=False,
        ),
    ]
