# Generated by Django 5.1.6 on 2025-03-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_employe_id_alter_cartebancaire_cvc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartebancaire',
            name='cvc',
            field=models.CharField(default='571', max_length=3),
        ),
    ]
