# Generated by Django 5.1.6 on 2025-03-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_cartebancaire_cvc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartebancaire',
            name='cvc',
            field=models.CharField(default='394', max_length=3),
        ),
    ]
