# Generated by Django 5.1.6 on 2025-03-06 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_client_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compte',
            old_name='client_id',
            new_name='client',
        ),
    ]
