# Generated by Django 5.1.6 on 2025-03-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_rename_client_id_compte_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.IntegerField(blank=True, editable=False, max_length=16, null=True, unique=True),
        ),
    ]
