# Generated by Django 5.1.6 on 2025-03-06 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_client_client_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client_id',
        ),
    ]
